name: Build and Upload

on:
  push:
    branches:
    - '*'

jobs:

  build-and-upload:
    runs-on: ubuntu-latest
    name: Build and Upload
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Sponge Plugin
        uses: actions/upload-artifact@v2
        with:
          path: sponge/build/lib/**
          if-no-files-found: error
      - name: Upload Sponge API
        uses: actions/upload-artifact@v2
        with:
          path: sponge-api/build/lib/**
          if-no-files-found: error
