name: Upload

on:
  push:
    branches:
    - 'master'

jobs:

  build-and-upload:
    runs-on: ubuntu-latest
    name: Build and Upload
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/**
          if-no-files-found: error
